version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "dependabot"
      include: "scope"
    #groups:
    #  minor-and-patch-updates:
    #    patterns:
    #      - "*"
    #    update-types:
    #      - "minor"
    #      - "patch"
    #ignore:
    #  - dependency-name: "*"
    #    update-types:
    #      - "version-update:semver-major"
