name: .NET

on: [ push, pull_request ]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 6.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    - name: Setup .NET 5.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build rm.Extensions.sln \
          -c Release
    # net6.0, net5.0 only as test csproj also targets others
    - name: Test net6.0
      run: |
        dotnet test tests/rm.ExtensionsTest/rm.ExtensionsTest.csproj \
          -c Release --no-build --no-restore \
          -f net6.0 \
          -v normal \
          --filter "TestCategory!=very.slow"
    - name: Test net5.0
      run: |
        dotnet test tests/rm.ExtensionsTest/rm.ExtensionsTest.csproj \
          -c Release --no-build --no-restore \
          -f net5.0 \
          -v normal \
          --filter "TestCategory!=very.slow"
