name: .NET

on: [ push, pull_request ]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 6.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    - name: Setup .NET 7.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build *sln \
          -c Release
    - name: Test net6.0
      if: success() || failure()
      run: |
        dotnet test tests/** \
          -c Release --no-build --no-restore \
          -f net6.0 \
          -l:"console;verbosity=normal" \
          --filter "TestCategory!=very.slow"
    - name: Test net7.0
      if: success() || failure()
      run: |
        dotnet test tests/** \
          -c Release --no-build --no-restore \
          -f net7.0 \
          -l:"console;verbosity=normal" \
          --filter "TestCategory!=very.slow"
